linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude-use-default: false
